source 'https://github.com/CocoaPods/Specs.git'

target 'APNPermissionRequest', :exclusive => true do
  pod "APNPermissionRequest", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "APNPermissionRequest", :path => "../"

  
end
